Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_auth/logout.html'), name='logout')
]

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('app_photo.urls')),
    path('auth/', include('app_auth.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/urls.py
from django.urls import path, include

from . import views

app_name = "app_photo"

urlpatterns = [
    path('', views.index, name='home'),  # app_photo:home
    path('free-pictures/', views.pictures, name='pictures'),
    path('upload/', views.upload, name='upload'),
    path('free-pictures/edit/<int:pic_id>', views.edit, name='edit'),
    path('free-pictures/remove/<int:pic_id>', views.remove, name='remove')
]

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/models.py
from pathlib import Path
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError


def validate_file_size(value):
    filesize = value.size

    if filesize > 1_000_000:
        raise ValidationError('Максимальний розмір файлу 1Мб')
    return value


def upload_image(instance, filename):
    upload_to = Path(instance.user.username) if instance.user else Path('images')
    ext = Path(filename).suffix
    new_filename = f"{uuid4().hex}{ext}"
    return str(upload_to / new_filename)


# Create your models here.
class Picture(models.Model):
    description = models.CharField(max_length=300)
    path = models.ImageField(upload_to=upload_image, validators=[validate_file_size])
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=None)

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'password')

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/forms.py
from django.forms import ModelForm, CharField, ImageField, TextInput, FileInput

from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=300, min_length=5,
                            widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    path = ImageField(widget=FileInput(attrs={"class": "form-control", "id": "formFile", "accept": "image/*"}))

    class Meta:
        model = Picture
        fields = ['description', 'path']

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.


class RegisterView(View):
    template_name = 'app_auth/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_photo:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено")
            return redirect(to="app_auth:signin")
        return render(request, self.template_name, {"form": form})

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/views.py
from pathlib import Path

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .forms import PictureForm
from .models import Picture


# Create your views here.

def index(request):
    return render(request, 'app_photo/index.html', context={"msg": "Hello world!"})


@login_required
def pictures(request):
    pics = Picture.objects.filter(user=request.user).all()
    return render(request, 'app_photo/pictures.html', context={"pics": pics})


@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            pic = form.save(commit=False)
            pic.user = request.user
            pic.save()
            return redirect(to="app_photo:pictures")
    return render(request, 'app_photo/upload.html', context={"form": form})


@login_required
def edit(request, pic_id):
    if request.method == 'POST':
        desc = request.POST.get('description')
        Picture.objects.filter(pk=pic_id, user=request.user).update(description=desc)
        return redirect(to="app_photo:pictures")
    pic = Picture.objects.filter(pk=pic_id, user=request.user).first()
    return render(request, 'app_photo/edit_desc.html', context={"pic": pic})


@login_required
def remove(request, pic_id):
    pic = Picture.objects.filter(pk=pic_id, user=request.user)
    file_path: Path = settings.MEDIA_ROOT / str(pic.first().path)
    if file_path.exists():
        file_path.unlink()
        pic.delete()
        print('Removed file')
    else:
        print('File ont removed')

    return redirect(to="app_photo:pictures")

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/templates/app_auth/login.html
{% extends 'app_photo/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/templates/app_auth/logout.html
{% extends 'app_photo/base.html' %}

{% block body %}

    <div class="container mt-3">
        <h1>Повертайтесь будь ласка!</h1>
    </div>

{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_auth/templates/app_auth/register.html
{% extends 'app_photo/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/templates/app_photo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_photo/main.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'app_photo:home' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'app_photo:pictures' %}">Pictures</a>
                <a class="nav-link" style="margin-right: auto" href="{% url 'app_photo:upload' %}">Upload</a>
                <div class="d-flex"><a class="nav-link" href="{% url 'app_auth:logout' %}">Logout</a></div>

                {% else %}
                <a class="nav-link" href="{% url 'app_auth:signup' %}">Register</a>
                <a class="nav-link" href="{% url 'app_auth:signin' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/templates/app_photo/edit_desc.html
{% extends 'app_photo/base.html' %}

{% block body %}
<div class="container mt-3">
    <form action="{% url 'app_photo:edit' pic.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <img src="{{pic.path.url}}" width=360 alt="...">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            <input type="text" value="{{pic.description}}" name="description">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/templates/app_photo/index.html
{% extends 'app_photo/base.html' %}

{% block body %}
    <div class="container mt-3">
        <h1>{{msg}}</h1>
    </div>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/templates/app_photo/pictures.html
{% extends 'app_photo/base.html' %}

{% block body %}
<div class="container mt-3">
    <h1>Pictures</h1>
    <div class="row">
        {% for pic in pics %}
        <div class="col-md-6">
            <div class="card" style="width: 18rem;">
                <img src="{{pic.path.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">{{pic.description}}</p>
                    <a href="{% url 'app_photo:edit' pic.id %}" class="btn btn-info">Edit description</a>
                    <a href="{% url 'app_photo:remove' pic.id %}" class="btn btn-danger">Delete picture</a>
                </div>
            </div>

        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/kuchma/m16_10_02/app_instagram/app_photo/templates/app_photo/upload.html
{% extends 'app_photo/base.html' %}

{% block body %}
<div class="container mt-3">
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form action="{% url 'app_photo:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            {{ form.description }}
            <div id="emailHelp" class="form-text">Description for picture</div>
            <span>{{form.errors.description}}</span>
        </div>
        <div class="mb-3">
            <label for="formFile" class="form-label">Default file input example</label>
            {{ form.path }}
            <span>{{form.errors.path}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}