Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path('author_create/', views.author_create, name='author_create'),
    path('quotes/<int:author_id>/', views.author_page, name='author_page'),
    path('quote_page/<int:tag_id>/', views.quote_page, name='quote_page'),
    path("<int:page>", views.main, name="root_paginate"),
]

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author_create/', views.author_create, name='author_create'),
    path('quotes/<int:author_id>/', views.author_page, name='author_page'),
    path('quote_page/<int:tag_id>/', views.quote_page, name='quote_page'),
    path('author/delete/', views.author_confirm_delete, name='author_confirm_delete'),
]

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import Author, Quote, Tag



def main(request, page=1):
    # page_number = request.GET.get('page', 1)
    quotes = Quote.objects.all().order_by('-created_at')  # Отримання всіх цитат із бази даних SQLite
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


def author_create(request):
    if request.method == 'POST':
        # Обробка POST-запиту
        fullname = request.POST.get('fullname', '')
        born_date = request.POST.get('born_date', '')
        born_location = request.POST.get('born_location', '')
        description = request.POST.get('description', '')
        quote_text = request.POST.get('quote', '')

        author = Author.objects.filter(fullname=fullname).first()

        if not author:
            author = Author.objects.create(
                fullname=fullname,
                born_date=born_date,
                born_location=born_location,
                description=description
            )

        Quote.objects.create(
            quote=quote_text,
            author=author
        )

        # Після успішного створення автора та цитати перенаправити куди-небудь
        return redirect('quotes:root')

    else:
        # Обробка GET-запиту (відображення форми для створення автора та цитати)
        return render(request, 'author/author_create.html')




def author_confirm_delete(request):
    if request.method == 'POST':
        full_name = request.POST.get('fullname', '')
        try:
            author = get_object_or_404(Author, fullname=full_name)
        except Author.DoesNotExist:
            return render(request, 'author_confirm_delete.html',
                          {'error': f"No Author matches the fullname '{full_name}'"})

        quotes = Quote.objects.filter(author=author)
        quotes.delete()
        author.delete()

        return redirect('quotes:root')

    return render(request, 'author_confirm_delete.html')


def author_page(request, author_id):
    # Отримати об'єкт автора за його ідентифікатором
    author = Author.objects.get(id=author_id)
    return render(request, 'author/author_page.html', {'author': author})


def quote_page(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    author = Author.objects.filter(quote__tags=tag).first()
    paginator = Paginator(quotes, 10)  # Показує 10 цитат на сторінці
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'author/quote_page.html', {'tag': tag, 'quotes': quotes, 'author': author, 'page_obj': page_obj})

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/templates/author/author_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Author</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>Are you sure you want to delete author "{{ author.fullname }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <label for="fullname">Author's Full Name:</label>
        <input type="text" id="fullname" name="fullname" required>
        <button type="submit">Delete Author</button>
    </form>
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
</div>
</body>
</html>

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/templates/author/author_create.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container">
    <h2>Create Author</h2>
    <form method="post" action="{% url 'quotes:author_create' %}" class="mt-4">
        {% csrf_token %}
        <div class="form-group mt-4">
            <label for="id_fullname">Author's Full Name:</label>
            <input type="text" id="id_fullname" name="fullname" required>
            <span class="text-danger">{{ form.errors.fullname }}</span>

            <label for="id_born_date">Born Date:</label>
            <input type="text" id="id_born_date" name="born_date" required>
            <span class="text-danger">{{ form.errors.born_date }}</span>

            <label for="id_born_location">Born Location:</label>
            <input type="text" id="id_born_location" name="born_location" required>
            <span class="text-danger">{{ form.errors.born_location }}</span>
        </div>
        <div class="form-group mt-4">
            <label for="id_description">Description:</label>
            <textarea id="id_description" name="description" class="form-control" required></textarea>
            <span class="text-danger">{{ form.errors.description }}</span>
        </div>
        <div class="form-group mt-4">
            <label for="quote">Quote:</label>
            <textarea name="quote" id="quote" class="form-control" required></textarea>
            <span class="text-danger">{{ form.errors.quote }}</span>
        </div>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>

    <div class="form-group mt-4">
        <form method="post" action="{% url 'quotes:author_confirm_delete' %}">
            {% csrf_token %}
            <label for="fullname">Author's Full Name:</label>
            <input type="text" id="fullname" name="fullname" required>
            <button type="submit" class="btn btn-danger">Delete Author</button>
        </form>
    </div>
</div>
{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/templates/author/author_page.html
{% extends 'quotes/../quotes/../quotes/base.html' %}

{% block content %}
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <div class="author-details">
                    <h3 class="author-title">{{ author.fullname }}</h3>
                    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
                            class="author-born-location">in {{ author.born_location }}</span></p>
                    <p><strong>Description:</strong></p>
                    <div class="author-description">
                        {{ author.description }}
                    </div>
                </div>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/quotes/templates/author/quote_page.html
{%extends 'quotes/../quotes/../quotes/base.html' %}

{% block content %}
<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h3> Viewing tag: <span style="color: blue;"> {{ tag }}</span></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">{{ quote.quote }}</span>
                    <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small></span>
                    <a href="{% url 'quotes:author_page' quote.author.id %}">(about)</a>
                </span>
                    <div class="tags">
                        Tags:
                        {% for tag in quote.tags.all %}
                        <a class="tag" href="{% url 'quotes:quote_page' tag.id %}">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div class="col-md-8">
                <nav>
                    <ul class="pager">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">←</span> Previous
                                </a>
                            </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="next">
                                <a href="?page={{ page_obj.next_page_number }}">
                                    Next <span aria-hidden="true">→</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        <div class="col-md-4 tags-box">
            {% for tag in quote.tags.all %}
                <a href="{% url 'quotes:quote_page' tag.id %}" class="btn btn-secondary">{{ tag }}</a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}