Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path('author_create/', views.author_create, name='author_create'),
    path('quotes/<int:author_id>/', views.author_page, name='author_page'),
    path('quote_page/<int:tag_id>/', views.quote_page, name='quote_page'),
    path("<int:page>", views.main, name="root_paginate"),
]

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/forms.py
from quotes.models import Author, Quote
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               label='Username',
                               help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.')

    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(),
                            label='Email'
                            )

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='Password',
                                help_text='Your password must contain at least 8 characters.')

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='Confirm Password',
                                help_text='Enter the same password as before, for verification.')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('fullname', 'born_date', 'born_location', 'description')
        labels = {
            'fullname': 'Full Name',
            'born_date': 'Born Date',
            'born_location': 'Born Location',
            'description': 'Description',
        }


class QuoteForm(forms.ModelForm):
    author_fullname = forms.CharField(max_length=50, required=False)

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author_fullname']

    def save(self, commit=True):
        author_fullname = self.cleaned_data['author_fullname']
        quote = super().save(commit=False)
        if author_fullname:
            author, created = Author.objects.get_or_create(fullname=author_fullname)
            quote.author = author
        if commit:
            quote.save()
        return quote

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='users:login')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(
            username=request.POST.get('username'), password=request.POST.get('password'))
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect('users:login')

        login(request, user)
        return redirect('quotes:root')

    return render(request, 'users/login.html', {"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/login.html
{% extends "quotes/../../../quotes/templates/quotes/../../../quotes/templates/quotes/base.html" %}

{% block content %}

    <div class="container">
        <h2>Login</h2>

        <form action="{% url 'users:login' %}" method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group mt-4">
                <label for="id_username">Username:</label>
                <input type="text" name="username" class="form-control" id="id_username">
            </div>

            <div class="form-group mt-4">
                <label for="id_password">Password:</label>
                <input type="password" name="password" class="form-control" id="id_password">
            </div>

            <div class="form-group mt-4">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Reset</button>
                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>


            <div class="small text-center">
                <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>

            </div>
        </form>
    </div>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

Python WEB 1.1/Modul_13_Python-WEB/hw_13 Django/hw_project/users/templates/users/signup.html
{% extends "quotes/../../../quotes/templates/quotes/../../../quotes/templates/quotes/base.html" %}

{% block content %}

<div class="container">
    <h2>Sign Up</h2>

    <form method="post" action="{% url 'users:signup' %}" class="mt-4">
        {% csrf_token %}
        <div class="form-group mt-4">
            <label for="id_username">Username:</label>
            <input type="text" name="username" class="form-control" id="id_username">
            <span class="text-danger">{{ form.errors.username }}</span>
        </div>
        <div class="form-group mt-4">
            <label for="id_email">Email:</label>
            <input type="text" name="email" class="form-control" id="id_email">
            <span class="text-danger">{{ form.errors.email }}</span>
        </div>
        <div class="form-group mt-4">
            <label for="id_password1">Password:</label>
            <input type="password" name="password1" class="form-control" id="id_password1">
            <span class="text-danger">{{ form.errors.password1 }}</span>
        </div>

        <div class="form-group mt-4">
            <label for="id_password2">Password confirmation:</label>
            <input type="password" name="password2" class="form-control" id="id_password2">
            <span class="text-danger">{{ form.errors.password2 }}</span>
        </div>

        <div class="form-group mt-4">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}