Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/urls.py
from django.urls import path
from . import views

app_name = "noteapp"

urlpatterns = [
    path('', views.index, name="index"),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
]

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noteapp/', include('noteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=150, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/users/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Note


class TagForm(ModelForm):

    name = CharField(
        min_length=3, max_length=25, required=True, widget=TextInput()
    )
    
    class Meta:
        model = Tag
        fields = ['name']


class NoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Tag, Note
from .forms import TagForm, NoteForm

def index(request):
    notes = Note.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    context = {
        "notes": notes
    }
    return render(request, "index.html", context)

@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.User)
    return render(request, 'detail.html', {"note": note})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)

        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            form.save()
            return redirect(to='noteapp:index')
        else:
            return render(request, 'tag.html', {'form': form})

    return render(request, 'tag.html', {'form': TagForm()})


@login_required
def note(request):
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='noteapp:index')
        else:
            return render(request, 'note.html', {"tags": tags, 'form': form})

    return render(request, 'note.html', {"tags": tags, 'form': NoteForm()})


@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).update(done=True)
    return redirect(to='noteapp:index')


@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='noteapp:index')

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm, ProfileForm


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='noteapp:index')


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='noteapp:index')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='noteapp:index')
        else:
            return render(request, 'signup.html', context={"form": form})

    return render(request, 'signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='noteapp:index')

    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )

        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='noteapp:index')

    return render(request, 'login.html', context={"form": LoginForm()})


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {'profile_form': profile_form})

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/noteapp" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/templates/detail.html
{% extends "base.html" %} {% load extract_tags %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">

    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'noteapp:note' %}" role="button">Add note</a></li>
            <li><a href="{% url 'noteapp:tag' %}" role="button">Add Tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% for note in notes %}
    <ul>
        <li>
            {% if not note.done %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="outline"> {{ note.name }} </a>
            <a href="{% url 'noteapp:set_done' note.id %}" role="button"> Mark Done </a>
            <a href="{% url 'noteapp:delete' note.id %}" role="button" class="contrast"> Delete note </a>
            {% else %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="secondary"><s>{{ note.name }}</s></a>
            {% endif %}
        </li>
    </ul>
    {% endfor %}
</main>
</body>
</html>

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/templates/note.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

Python WEB 1.1/Modul_10_Python-WEB/lesson/preparation/notes/noteapp/templates/tag.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}